name: collision_detection
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  firebase_core: ^3.8.0
  firebase_database: ^11.2.0
  fl_chart: ^0.69.2
  firebase_auth: ^5.3.4
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  geolocator: ^13.0.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  sensors_plus: ^6.1.1
  telephony: ^0.2.0
  tflite_flutter: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
